### ISSUE TITLE
potential tweets for phase 1

### ISSUE THREAD

**Issue by Gala4peace** [WeRockTech/HelloPeaceBot#2]
Happy international #PeaceDay! Join us in our challenge to build peace today.

Today we are working to build peace together, wanna join us? #PeaceChallenge #PeaceDay 

Happy #PeaceDay! We are making our bit for #Peace, by the hour! Join our challenge

Building peace by the hour Happy #PeaceDay
"An eye for an eye will only make the whole world blind" Mahatma Gandhi 
We are celebrating #PeaceDay building peace hour after hour, join us!

**Comment by tanyapowell** [comment]
@Gala4peace have added all of these 😄
